import type {
  User,
  Epic,
  Milestone,
  Ticket,
  TicketType,
  TicketStatus,
  Priority,
  Sprint,
  Comment,
  Notification,
  ActivityEntry,
} from "./types";

// ─── Users ──────────────────────────────────────────────────────────
// Two-role world: PM or Engineer. Former designer/leadership/em/admin/guest
// users are folded into one of these two.
export const seedUsers: User[] = [
  {
    id: "u_albert",
    email: "pm@spxexpress.com",
    displayName: "Albert Halim",
    handle: "albert.halim",
    role: "pm",
    capacityPoints: 0,
    expertiseTags: ["forecasting", "routing"],
    status: "available",
    initials: "AH",
    colorKey: "a",
  },
  {
    id: "u_diana",
    email: "pm-lead@spxexpress.com",
    displayName: "Diana Wijaya",
    handle: "diana.wijaya",
    role: "pm",
    capacityPoints: 0,
    expertiseTags: ["strategy", "platform"],
    status: "in_meeting",
    initials: "DW",
    colorKey: "b",
  },
  {
    id: "u_andre",
    email: "eng@spxexpress.com",
    displayName: "Andre Halim",
    handle: "andre.halim",
    role: "engineer",
    capacityPoints: 8,
    expertiseTags: ["forecasting", "python", "ml"],
    status: "available",
    initials: "AH",
    colorKey: "c",
  },
  {
    id: "u_sari",
    email: "sari@spxexpress.com",
    displayName: "Sari Wibowo",
    handle: "sari.wibowo",
    role: "engineer",
    capacityPoints: 6,
    expertiseTags: ["forecasting", "tech-lead"],
    status: "available",
    initials: "SW",
    colorKey: "e",
  },
  {
    id: "u_bayu",
    email: "bayu@spxexpress.com",
    displayName: "Bayu Pratama",
    handle: "bayu.pratama",
    role: "engineer",
    capacityPoints: 8,
    expertiseTags: ["data-eng", "spark"],
    status: "available",
    initials: "BP",
    colorKey: "f",
  },
  {
    id: "u_devi",
    email: "devi@spxexpress.com",
    displayName: "Devi Anggraini",
    handle: "devi.anggraini",
    role: "engineer",
    capacityPoints: 8,
    expertiseTags: ["mobile", "android"],
    status: "available",
    initials: "DA",
    colorKey: "a",
  },
  {
    id: "u_mira",
    email: "mira@spxexpress.com",
    displayName: "Mira Rachmadi",
    handle: "mira.rachmadi",
    role: "engineer",
    capacityPoints: 5,
    expertiseTags: ["python", "ml"],
    status: "available",
    initials: "MR",
    colorKey: "b",
  },
  {
    id: "u_kev",
    email: "kev@spxexpress.com",
    displayName: "Kevin Surya",
    handle: "kevin.surya",
    role: "engineer",
    capacityPoints: 8,
    expertiseTags: ["backend", "go"],
    status: "ooo",
    initials: "KS",
    colorKey: "c",
  },
];

export const usersByEmail = Object.fromEntries(seedUsers.map((u) => [u.email, u]));

// ─── Sprints ────────────────────────────────────────────────────────
const today = new Date("2026-05-11");
const isoDate = (d: Date) => d.toISOString().slice(0, 10);
const addDays = (d: Date, n: number) => {
  const x = new Date(d);
  x.setDate(x.getDate() + n);
  return x;
};

export const seedSprints: Sprint[] = [
  {
    id: "sp_w17",
    key: "W17-2026",
    startDate: isoDate(addDays(today, -21)),
    endDate: isoDate(addDays(today, -15)),
    state: "closed",
    committedPoints: 28,
    shippedPoints: 26,
    committedAt: isoDate(addDays(today, -22)),
  },
  {
    id: "sp_w18",
    key: "W18-2026",
    startDate: isoDate(addDays(today, -14)),
    endDate: isoDate(addDays(today, -8)),
    state: "closed",
    committedPoints: 30,
    shippedPoints: 29,
    committedAt: isoDate(addDays(today, -15)),
  },
  {
    id: "sp_w19",
    key: "W19-2026",
    startDate: isoDate(addDays(today, -7)),
    endDate: isoDate(addDays(today, -1)),
    state: "closed",
    committedPoints: 31,
    shippedPoints: 27,
    committedAt: isoDate(addDays(today, -8)),
  },
  {
    id: "sp_w20",
    key: "W20-2026",
    startDate: isoDate(today),
    endDate: isoDate(addDays(today, 6)),
    state: "active",
    committedPoints: 34,
    shippedPoints: 12,
    committedAt: isoDate(addDays(today, -1)),
  },
  {
    id: "sp_w21",
    key: "W21-2026",
    startDate: isoDate(addDays(today, 7)),
    endDate: isoDate(addDays(today, 13)),
    state: "planning",
    committedPoints: 0,
    shippedPoints: 0,
    committedAt: null,
  },
];

// ─── Epics ──────────────────────────────────────────────────────────
/**
 * Flattened model: each former Project becomes an Epic, keyed by its
 * domain code (CDN, RTE, MAD, HUB, DRV) so child tickets like CDN-3504
 * read as "ticket #3504 under epic CDN" without a hidden mapping table.
 *
 * The old top-level Epics ("Forecasting v2", "4PL SAPX Madura", …) are
 * promoted to the soft `program` label so groups of related epics still
 * cluster on the portfolio surface.
 */
export const seedEpics: Epic[] = [
  {
    id: "ep_cdn",
    key: "CDN",
    title: "Forecasting model retrain pipeline",
    thesis:
      "Replace the brittle daily-batch forecaster with a streaming model that picks up demand shocks within 4 hours. Cuts driver no-show cost by 28%.",
    description:
      "Daily retraining pipeline with drift detection, calibration, and automated rollback.",
    quarter: "Q2 2026",
    programs: ["FM", "FINOPS", "BPOM"],
    status: "in_progress",
    health: "on_track",
    pmPicId: "u_albert",
    startDate: "2026-04-01",
    targetEndDate: "2026-05-30",
    tags: ["ml", "forecasting"],
    position: 0,
  },
  {
    id: "ep_rte",
    key: "RTE",
    title: "Ferry timetable awareness",
    thesis:
      "Make the router aware of Madura ferry windows; reroute pre-cutoff parcels so 4PL Madura can hit cutoffs reliably.",
    description: "Static ferry timetable loader + pre-cutoff reroute scoring.",
    quarter: "Q2 2026",
    programs: ["LM", "Expansion"],
    status: "in_progress",
    health: "at_risk",
    pmPicId: "u_albert",
    startDate: "2026-04-15",
    targetEndDate: "2026-05-25",
    tags: ["routing", "4pl"],
    position: 1,
  },
  {
    id: "ep_mad",
    key: "MAD",
    title: "Madura ops dashboard",
    thesis:
      "Stand up a parallel ops dashboard for Madura station so the local team can see cutoff risk before it happens.",
    description: "Cutoff alerts, parcel-flow visualisation, hourly throughput.",
    quarter: "Q2 2026",
    programs: ["LM", "Expansion", "BPOM"],
    status: "in_progress",
    health: "on_track",
    pmPicId: "u_albert",
    startDate: "2026-04-20",
    targetEndDate: "2026-06-05",
    tags: ["4pl", "dashboards"],
    position: 2,
  },
  {
    id: "ep_hub",
    key: "HUB",
    title: "Hub capacity hourly signals",
    thesis:
      "Surface hub-level capacity by hour so sorting can flex line balancing pre-emptively instead of reactively.",
    description: "Ingest hourly throughput from each hub sortation line; surface to sorting leads.",
    quarter: "Q2 2026",
    programs: ["LM", "FM", "CCTV"],
    status: "in_progress",
    health: "on_track",
    pmPicId: "u_albert",
    startDate: "2026-04-22",
    targetEndDate: "2026-06-10",
    tags: ["sorting", "capacity"],
    position: 3,
  },
  {
    id: "ep_drv",
    key: "DRV",
    title: "Driver app reliability",
    thesis:
      "Reduce driver app friction (taps per delivery, timestamp accuracy, offline fallback) to raise daily completion by 6%.",
    description: "Fix Android 14 timestamp drift; reduce taps per delivery; offline fallback.",
    quarter: "Q2 2026",
    programs: ["LM", "CCTV"],
    status: "in_progress",
    health: "blocked",
    pmPicId: "u_diana",
    startDate: "2026-04-28",
    targetEndDate: "2026-06-30",
    tags: ["mobile", "driver"],
    position: 4,
  },
  {
    id: "ep_obs",
    key: "OBS",
    title: "Eng observability baseline",
    thesis:
      "Every service emits the same five golden signals through Sentry + Grafana. Unblocks postmortems and SLAs.",
    description: "Sentry + Grafana baseline across services. Platform-wide.",
    quarter: "Q3 2026",
    programs: ["FINOPS"],
    status: "backlog",
    health: "not_started",
    pmPicId: "u_diana",
    startDate: "2026-07-01",
    targetEndDate: "2026-09-30",
    tags: ["platform"],
    position: 5,
  },
];

// ─── Tickets ────────────────────────────────────────────────────────
const ac = (text: string, done = false) => ({
  id: `ac_${Math.random().toString(36).slice(2, 8)}`,
  text,
  done,
});

/**
 * Compact factory for tickets that belong to a prior, already-closed
 * sprint. Used only by /sprint-close to give the retro view a real
 * shipped + carry-over corpus. Defaults to status="done" / not carried.
 */
const closedTicket = (opts: {
  id: string;
  key: string;
  type: TicketType;
  title: string;
  epicId: string | null;
  sprintId: string;
  authorId: string;
  assigneeId: string;
  storyPoints: number;
  closedDaysAgo: number;
  status?: TicketStatus;
  carryOver?: boolean;
  priority?: Priority;
  tags?: string[];
  severity?: "S1" | "S2" | "S3";
}): Ticket => {
  const status = opts.status ?? "done";
  const isShipped = status === "done" || status === "verified";
  return {
    id: opts.id,
    key: opts.key,
    type: opts.type,
    title: opts.title,
    description: `Carried in sprint ${opts.sprintId.replace(/^sp_/, "").toUpperCase()}.`,
    acceptanceCriteria: [],
    epicId: opts.epicId,
    priority: opts.priority ?? "P2",
    status,
    authorId: opts.authorId,
    tags: opts.tags ?? [],
    pickedForSprint: true,
    picklistRank: null,
    storyPoints: opts.storyPoints,
    concernFlags: [],
    assigneeId: opts.assigneeId,
    sprintId: opts.sprintId,
    startedAt: isoDate(addDays(today, -(opts.closedDaysAgo + 4))),
    closedAt: isShipped ? isoDate(addDays(today, -opts.closedDaysAgo)) : null,
    linkedWork: [],
    carryOver: opts.carryOver ?? false,
    createdAt: isoDate(addDays(today, -(opts.closedDaysAgo + 7))),
    ...(opts.severity ? { severity: opts.severity } : {}),
  };
};

// ─── Milestones (waterfall phases per Epic) ─────────────────────────
// PRD § 13.2: pending → in_progress → complete, sequentially gated by order.
// First milestone enters in_progress automatically when the Epic's
// startDate is reached. Mix of completed / in-flight / pending so the
// computed health signals on /epics + /portfolio have variety.
const mDays = (n: number) => isoDate(addDays(today, n));

export const seedMilestones: Milestone[] = [
  // CDN — Forecasting model retrain (started 30d ago, target +30d)
  // 3 of 5 phases done, currently in Test.
  { id: "m_cdn_1", epicId: "ep_cdn", order: 1, name: "Requirements", targetDate: mDays(-25), entryCriteria: "PM signs off on thesis + program tags.", exitCriteria: "Training dataset path validated; governance OK.", status: "complete", actualDate: mDays(-26) },
  { id: "m_cdn_2", epicId: "ep_cdn", order: 2, name: "Design",       targetDate: mDays(-18), entryCriteria: "Requirements complete.",                    exitCriteria: "ML system design doc signed by EM.",                  status: "complete", actualDate: mDays(-17) },
  { id: "m_cdn_3", epicId: "ep_cdn", order: 3, name: "Build",        targetDate: mDays(-5),  entryCriteria: "Design approved.",                          exitCriteria: "Drift gate + calibration pipeline merged.",            status: "complete", actualDate: mDays(-3) },
  { id: "m_cdn_4", epicId: "ep_cdn", order: 4, name: "Test",         targetDate: mDays(12),  entryCriteria: "Build complete.",                           exitCriteria: "Eval suite shows MAPE within ±2% vs baseline.",        status: "in_progress", actualDate: null },
  { id: "m_cdn_5", epicId: "ep_cdn", order: 5, name: "Deploy",       targetDate: mDays(28),  entryCriteria: "Test passes.",                              exitCriteria: "Canary 10% > 48h with no degradation.",                status: "pending", actualDate: null },

  // RTE — Ferry timetable awareness (in_progress, design slipping a bit)
  { id: "m_rte_1", epicId: "ep_rte", order: 1, name: "Requirements", targetDate: mDays(-15), entryCriteria: "PM signs thesis.",          exitCriteria: "PT ASDP feed access validated.",          status: "complete",     actualDate: mDays(-13) },
  { id: "m_rte_2", epicId: "ep_rte", order: 2, name: "Design",       targetDate: mDays(-8),  entryCriteria: "Requirements OK.",          exitCriteria: "Reroute scoring spec frozen.",            status: "in_progress",  actualDate: null },
  { id: "m_rte_3", epicId: "ep_rte", order: 3, name: "Build",        targetDate: mDays(3),   entryCriteria: "Design OK.",                exitCriteria: "Loader + scorer merged to main.",         status: "pending",      actualDate: null },
  { id: "m_rte_4", epicId: "ep_rte", order: 4, name: "Deploy",       targetDate: mDays(14),  entryCriteria: "Build complete.",           exitCriteria: "Canary OK on Madura traffic for 72h.",    status: "pending",      actualDate: null },

  // MAD — Madura ops dashboard (5 phases, 2 done, currently building)
  { id: "m_mad_1", epicId: "ep_mad", order: 1, name: "Requirements", targetDate: mDays(-12), entryCriteria: "PM signs thesis.",          exitCriteria: "Station ops sign off on widget set.",     status: "complete",    actualDate: mDays(-11) },
  { id: "m_mad_2", epicId: "ep_mad", order: 2, name: "Design",       targetDate: mDays(-4),  entryCriteria: "Requirements OK.",          exitCriteria: "Dashboard mock approved.",                status: "complete",    actualDate: mDays(-4)  },
  { id: "m_mad_3", epicId: "ep_mad", order: 3, name: "Build",        targetDate: mDays(15),  entryCriteria: "Design OK.",                exitCriteria: "Cutoff alerts + parcel-flow live.",       status: "in_progress", actualDate: null },
  { id: "m_mad_4", epicId: "ep_mad", order: 4, name: "Test",         targetDate: mDays(28),  entryCriteria: "Build complete.",           exitCriteria: "End-to-end UAT pass.",                    status: "pending",     actualDate: null },
  { id: "m_mad_5", epicId: "ep_mad", order: 5, name: "Deploy",       targetDate: mDays(38),  entryCriteria: "Test passes.",              exitCriteria: "Madura station team trained.",            status: "pending",     actualDate: null },

  // HUB — Hub capacity hourly signals
  { id: "m_hub_1", epicId: "ep_hub", order: 1, name: "Requirements", targetDate: mDays(-6),  entryCriteria: "PM signs thesis.",          exitCriteria: "Sortation team signs scope.",             status: "complete",    actualDate: mDays(-5)  },
  { id: "m_hub_2", epicId: "ep_hub", order: 2, name: "Build",        targetDate: mDays(20),  entryCriteria: "Requirements OK.",          exitCriteria: "Hourly aggregator + UI shipped.",         status: "in_progress", actualDate: null },
  { id: "m_hub_3", epicId: "ep_hub", order: 3, name: "Test",         targetDate: mDays(35),  entryCriteria: "Build complete.",           exitCriteria: "Signals match 6h spot checks.",           status: "pending",     actualDate: null },
  { id: "m_hub_4", epicId: "ep_hub", order: 4, name: "Deploy",       targetDate: mDays(43),  entryCriteria: "Test passes.",              exitCriteria: "Sorting leads onboarded.",                status: "pending",     actualDate: null },

  // DRV — Driver app reliability (blocked — past target with work remaining)
  { id: "m_drv_1", epicId: "ep_drv", order: 1, name: "Requirements", targetDate: mDays(-20), entryCriteria: "PM signs thesis.",          exitCriteria: "Driver-app scope frozen.",                status: "complete",    actualDate: mDays(-19) },
  { id: "m_drv_2", epicId: "ep_drv", order: 2, name: "Build",        targetDate: mDays(-10), entryCriteria: "Requirements OK.",          exitCriteria: "Timestamp drift fix + offline fallback.", status: "in_progress", actualDate: null },
  { id: "m_drv_3", epicId: "ep_drv", order: 3, name: "Deploy",       targetDate: mDays(-2),  entryCriteria: "Build complete.",           exitCriteria: "Canary cohort 10% drivers Jakarta.",      status: "pending",     actualDate: null },

  // OBS — Eng observability baseline (Q3, not started yet — no milestones until kickoff)
];

export const seedTickets: Ticket[] = [
  {
    id: "t_3504",
    key: "CDN-3504",
    type: "engineering",
    title: "Drift detection on retrain pipeline",
    description:
      "Detect when daily retrain produces a model whose validation MAPE deviates >12% from the trailing 7-day baseline. Block promotion and alert PM + EM channel.",
    acceptanceCriteria: [
      ac("MAPE deviation calc runs nightly", true),
      ac("Alert sent to #forecasting-ml channel on breach"),
      ac("Promotion blocked and rolled back automatically"),
      ac("Dashboard surface shows current vs baseline"),
    ],
    epicId: "ep_cdn",
    priority: "P1",
    status: "in_progress",
    authorId: "u_albert",
    tags: ["ml", "forecasting"],
    pickedForSprint: true,
    picklistRank: 1,
    storyPoints: 5,
    concernFlags: [],
    assigneeId: "u_andre",
    sprintId: "sp_w20",
    startedAt: isoDate(addDays(today, -1)),
    closedAt: null,
    linkedWork: [{ type: "blocks", ticketKey: "CDN-3505" }],
    carryOver: false,
    createdAt: isoDate(addDays(today, -10)),
  },
  {
    id: "t_3505",
    key: "CDN-3505",
    type: "engineering",
    title: "Calibration layer after drift gate",
    description:
      "Once drift gate is in, layer in temperature scaling so the published probabilities match observed frequencies within ±2%.",
    acceptanceCriteria: [
      ac("Temperature scale fit per region"),
      ac("Calibration plot included in dashboard"),
      ac("ECE < 2% on held-out week"),
    ],
    epicId: "ep_cdn",
    priority: "P2",
    status: "scheduled",
    authorId: "u_andre",
    tags: ["ml", "forecasting"],
    pickedForSprint: true,
    picklistRank: 2,
    storyPoints: 8,
    concernFlags: ["needs decomposition"],
    assigneeId: "u_mira",
    sprintId: "sp_w20",
    startedAt: null,
    closedAt: null,
    linkedWork: [{ type: "blocked_by", ticketKey: "CDN-3504" }],
    carryOver: false,
    createdAt: isoDate(addDays(today, -8)),
    aiSuggestedPoints: {
      value: 5,
      confidence: 0.78,
      reasoning:
        "Similar tickets CDN-3201 and CDN-3380 (calibration work) shipped at 5 pts and 5 pts. The added cross-region split is incremental.",
    },
  },
  {
    id: "t_4421",
    key: "BUG-4421",
    type: "bug",
    title: "Android 14 driver timestamps drift by ~3 min",
    description: "Driver delivery timestamps on Android 14 devices are consistently ~3 min ahead of server time.",
    acceptanceCriteria: [],
    epicId: "ep_drv",
    priority: "P0",
    status: "in_progress",
    authorId: "u_ronaldo",
    tags: ["mobile", "android", "android-14"],
    pickedForSprint: true,
    picklistRank: 3,
    storyPoints: 3,
    concernFlags: [],
    assigneeId: "u_devi",
    sprintId: "sp_w20",
    startedAt: isoDate(addDays(today, 0)),
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -3)),
    severity: "S1",
    reproSteps: "1. Install driver app on Pixel 8 (A14)\n2. Mark delivery complete\n3. Compare device clock vs server log",
    expectedVsActual:
      "Expected: timestamp within ±10s of server.\nActual: timestamp ~3 min ahead, consistently.",
    affectedScope: "All A14 devices, ~340 active drivers Jakarta region",
    sentryLink: "https://sentry.io/issues/INST-12842",
  },
  {
    id: "t_891",
    key: "RTE-891",
    type: "engineering",
    title: "Ferry timetable static loader",
    description: "Daily pull of Madura ferry timetable from PT ASDP feed; persist as routing dataset.",
    acceptanceCriteria: [
      ac("Pull job runs 04:00 SGT daily", true),
      ac("Fallback to yesterday's table on fetch failure"),
      ac("Coverage logged to ops dashboard"),
    ],
    epicId: "ep_rte",
    priority: "P1",
    status: "review",
    authorId: "u_albert",
    tags: ["routing", "4pl"],
    pickedForSprint: true,
    picklistRank: 4,
    storyPoints: 3,
    concernFlags: [],
    assigneeId: "u_bayu",
    sprintId: "sp_w20",
    startedAt: isoDate(addDays(today, -2)),
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -6)),
  },
  {
    id: "t_892",
    key: "RTE-892",
    type: "engineering",
    title: "Ferry-aware reroute pre-cutoff",
    description: "Reroute parcels that would miss the next ferry to the alternate land path.",
    acceptanceCriteria: [
      ac("Reroute triggered when parcel ETA > ferry cutoff − 30m"),
      ac("Notification fires to dispatch ops"),
    ],
    epicId: "ep_rte",
    priority: "P1",
    status: "in_progress",
    authorId: "u_albert",
    tags: ["routing", "4pl"],
    pickedForSprint: true,
    picklistRank: 5,
    storyPoints: 8,
    concernFlags: ["blocked by RTE-891"],
    assigneeId: "u_bayu",
    sprintId: "sp_w20",
    startedAt: isoDate(addDays(today, -1)),
    closedAt: null,
    linkedWork: [{ type: "blocked_by", ticketKey: "RTE-891" }],
    carryOver: false,
    createdAt: isoDate(addDays(today, -5)),
    blocked: { reason: "Awaiting RTE-891 in review", blockerKey: "RTE-891" },
  },
  {
    id: "t_3601",
    key: "CDN-3601",
    type: "engineering",
    title: "Region-aware seasonality features",
    description: "Add per-region seasonality decomposition into the forecaster feature set.",
    acceptanceCriteria: [ac("12 regions cover Java + Sumatra"), ac("Backtested against W12–W18")],
    epicId: "ep_cdn",
    priority: "P2",
    status: "scheduled",
    authorId: "u_andre",
    tags: ["ml"],
    pickedForSprint: true,
    picklistRank: 6,
    storyPoints: 5,
    concernFlags: [],
    assigneeId: "u_andre",
    sprintId: "sp_w20",
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -4)),
  },
  {
    id: "t_3700",
    key: "TCH-3700",
    type: "tech_task",
    title: "Migrate retrain orchestrator from cron to Argo",
    description: "Lift our retrain DAG out of cron + bash into Argo Workflows for retries + observability.",
    acceptanceCriteria: [ac("Argo DAG green for 3 nights"), ac("Cron disabled with revert plan documented")],
    epicId: "ep_cdn",
    priority: "P2",
    status: "done",
    authorId: "u_sari",
    tags: ["platform"],
    pickedForSprint: true,
    picklistRank: 7,
    storyPoints: 5,
    concernFlags: [],
    assigneeId: "u_mira",
    sprintId: "sp_w20",
    startedAt: isoDate(addDays(today, -3)),
    closedAt: isoDate(addDays(today, -1)),
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -7)),
    blastRadius: "Retrain pipeline only; staging tested 1 week prior",
    rollbackPlan: "Re-enable cron job; Argo DAG paused",
    migrationWindow: "Sun 03:00–05:00 SGT",
  },
  // Ad-hoc P1 bug (no project) - for ad-hoc lane demo
  {
    id: "t_4500",
    key: "BUG-4500",
    type: "bug",
    title: "Dashboard tile crash on Safari 17",
    description: "Capacity dashboard tile crashes on Safari 17 when WebGL not available.",
    acceptanceCriteria: [],
    epicId: null,
    priority: "P1",
    status: "in_progress",
    authorId: "u_diana",
    tags: ["frontend", "safari"],
    pickedForSprint: true,
    picklistRank: null,
    storyPoints: 2,
    concernFlags: [],
    assigneeId: "u_andre",
    sprintId: "sp_w20",
    startedAt: isoDate(today),
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(today),
    severity: "S2",
    reproSteps: "Open dashboard in Safari 17 with WebGL disabled",
    expectedVsActual: "Should fall back to canvas; instead the page crashes.",
    affectedScope: "Internal ops dashboard users on Safari 17 (~12 people)",
  },
  // Recently-filed backlog tickets ────────────────────────
  {
    id: "t_tri_1",
    key: "CDN-3712",
    type: "engineering",
    title: "Cache invalidation on region config change",
    description:
      "When a region config is updated in the admin UI, the routing cache for that region should invalidate within 60s.",
    acceptanceCriteria: [],
    epicId: null,
    priority: "P2",
    status: "backlog",
    authorId: "u_diana",
    tags: [],
    pickedForSprint: false,
    picklistRank: null,
    storyPoints: null,
    concernFlags: [],
    assigneeId: null,
    sprintId: null,
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -2)),
    aiSuggestedParent: {
      epicKey: "HUB",
      confidence: 0.86,
      reasoning:
        "Author Diana files cache work most often in Hub capacity; the description mentions region config which lives in the Hub project.",
    },
  },
  {
    id: "t_tri_2",
    key: "BUG-4540",
    type: "bug",
    title: "Push notification arrives twice on certain devices",
    description: "Driver app push notifications fire twice on Samsung S22 with One UI 6.0.",
    acceptanceCriteria: [],
    epicId: null,
    priority: "P1",
    status: "backlog",
    authorId: "u_ronaldo",
    tags: ["mobile"],
    pickedForSprint: false,
    picklistRank: null,
    storyPoints: null,
    concernFlags: [],
    assigneeId: null,
    sprintId: null,
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -1)),
    severity: "S2",
    reproSteps: "Send any push, observe doubled receipt on Samsung S22 (OneUI 6.0).",
    expectedVsActual: "Expected: one notification. Actual: two.",
    affectedScope: "Estimated ~60 drivers on Samsung S22 / OneUI 6",
    aiSuggestedParent: {
      epicKey: "DRV",
      confidence: 0.94,
      reasoning:
        "Title + repro steps match the Driver app reliability project; PRJ-152 already owns Android timestamp work.",
    },
    aiDuplicates: [{ ticketKey: "BUG-4421", confidence: 0.42 }],
  },
  {
    id: "t_tri_3",
    key: "CDN-3713",
    type: "engineering",
    title: "Backfill missing 4PL Madura ledger entries from April",
    description: "Some ledger entries between Apr 18–22 are missing in the Madura ops view.",
    acceptanceCriteria: [],
    epicId: null,
    priority: "P2",
    status: "backlog",
    authorId: "u_sari",
    tags: [],
    pickedForSprint: false,
    picklistRank: null,
    storyPoints: null,
    concernFlags: [],
    assigneeId: null,
    sprintId: null,
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -3)),
    aiSuggestedParent: {
      epicKey: "MAD",
      confidence: 0.71,
      reasoning: "Mentions Madura ops view; PRJ-131 owns Madura dashboards.",
    },
  },
  {
    id: "t_tri_4",
    key: "CDN-3714",
    type: "engineering",
    title: "Add P95 latency widget to forecasting dashboard",
    description: "Need at-a-glance latency for the inference endpoint.",
    acceptanceCriteria: [],
    epicId: null,
    priority: "P2",
    status: "backlog",
    authorId: "u_andre",
    tags: [],
    pickedForSprint: false,
    picklistRank: null,
    storyPoints: null,
    concernFlags: [],
    assigneeId: null,
    sprintId: null,
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(today),
    aiSuggestedParent: {
      epicKey: "CDN",
      confidence: 0.83,
      reasoning: "Inference latency is a Forecasting concern; PRJ-118 owns dashboards there.",
    },
  },
  // Backlog candidates ──────────────────────────────────────
  {
    id: "t_b1",
    key: "CDN-3801",
    type: "engineering",
    title: "Per-hub override for sortation throughput targets",
    description: "Ops should be able to set a per-hub override window for throughput targets.",
    acceptanceCriteria: [ac("Override UI in admin"), ac("Audit log entry per change")],
    epicId: "ep_hub",
    priority: "P2",
    status: "backlog",
    authorId: "u_albert",
    tags: ["sorting"],
    pickedForSprint: false,
    picklistRank: null,
    storyPoints: null,
    concernFlags: [],
    assigneeId: null,
    sprintId: null,
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -12)),
    aiSuggestedPoints: { value: 5, confidence: 0.81, reasoning: "Pattern matches CDN-3502 admin overrides (5 pts shipped W17)." },
  },
  {
    id: "t_b2",
    key: "RTE-902",
    type: "engineering",
    title: "Alternate land path scoring for Madura cutoff misses",
    description: "Score alternate land paths so router picks the lowest-cost option when ferry cutoff is missed.",
    acceptanceCriteria: [ac("Cost = distance × congestion factor × SLA risk")],
    epicId: "ep_rte",
    priority: "P1",
    status: "backlog",
    authorId: "u_albert",
    tags: ["routing"],
    pickedForSprint: false,
    picklistRank: null,
    storyPoints: null,
    concernFlags: [],
    assigneeId: null,
    sprintId: null,
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -9)),
    aiSuggestedPoints: { value: 8, confidence: 0.74, reasoning: "Routing scoring tickets average 8 pts (n=6 last quarter)." },
  },
  {
    id: "t_b3",
    key: "BUG-4602",
    type: "bug",
    title: "Drift detection alert sometimes duplicated in Lark",
    description: "Drift alerts occasionally fire twice within 30s.",
    acceptanceCriteria: [],
    epicId: "ep_cdn",
    priority: "P2",
    status: "backlog",
    authorId: "u_diana",
    tags: ["alerting"],
    pickedForSprint: false,
    picklistRank: null,
    storyPoints: null,
    concernFlags: [],
    assigneeId: null,
    sprintId: null,
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -32)), // stale
    severity: "S3",
    reproSteps: "Trigger drift via shadow data; observe Lark.",
    expectedVsActual: "Expected: one alert. Actual: two within 30s.",
    affectedScope: "#forecasting-ml channel",
  },
  {
    id: "t_b4",
    key: "TCH-3920",
    type: "tech_task",
    title: "Upgrade router service to Go 1.23",
    description: "Routine runtime upgrade with associated lib bumps.",
    acceptanceCriteria: [ac("All tests green"), ac("Canary 24h")],
    epicId: "ep_rte",
    priority: "P2",
    status: "backlog",
    authorId: "u_sari",
    tags: ["platform"],
    pickedForSprint: false,
    picklistRank: null,
    storyPoints: null,
    concernFlags: [],
    assigneeId: null,
    sprintId: null,
    startedAt: null,
    closedAt: null,
    linkedWork: [],
    carryOver: false,
    createdAt: isoDate(addDays(today, -5)),
    blastRadius: "Router service in all regions",
    rollbackPlan: "Pin to 1.22 image, reboot pods",
    aiSuggestedPoints: { value: 3, confidence: 0.88, reasoning: "Past Go minor upgrades have been 2–3 pts." },
  },

  // ─── Closed-sprint corpus (W17 · W18 · W19) ───
  // Feeds /sprint-close so the retro page has real shipped tickets to
  // tally and a couple of carry-overs to surface. Numbers line up with
  // the matching Sprint.committedPoints / shippedPoints in seedSprints.

  // W19 - 6 shipped (27 pts), 2 carry-over (4 pts); committed = 31
  closedTicket({ id: "t_w19_1", key: "RTE-852",  type: "engineering", title: "Ferry timetable v1 loader",         epicId: "ep_rte", sprintId: "sp_w19", authorId: "u_albert",  assigneeId: "u_devi",   storyPoints: 8, closedDaysAgo: 2, priority: "P1", tags: ["routing", "4pl"] }),
  closedTicket({ id: "t_w19_2", key: "MAD-310",  type: "engineering", title: "Madura cutoff alert v1",            epicId: "ep_mad", sprintId: "sp_w19", authorId: "u_albert",  assigneeId: "u_sari",   storyPoints: 5, closedDaysAgo: 2, tags: ["4pl", "alerts"] }),
  closedTicket({ id: "t_w19_3", key: "HUB-104",  type: "engineering", title: "Hourly throughput ingest",          epicId: "ep_hub", sprintId: "sp_w19", authorId: "u_diana",   assigneeId: "u_mira",   storyPoints: 5, closedDaysAgo: 3, tags: ["sorting"] }),
  closedTicket({ id: "t_w19_4", key: "CDN-3490", type: "engineering", title: "Drift dashboard surface",           epicId: "ep_cdn", sprintId: "sp_w19", authorId: "u_albert",  assigneeId: "u_andre",  storyPoints: 3, closedDaysAgo: 1, tags: ["ml", "dashboards"], status: "verified" }),
  closedTicket({ id: "t_w19_5", key: "BUG-4400", type: "bug",         title: "Driver app cold-start crash (A14)", epicId: "ep_drv", sprintId: "sp_w19", authorId: "u_ronaldo", assigneeId: "u_devi",   storyPoints: 3, closedDaysAgo: 4, priority: "P0", tags: ["mobile", "android"], status: "verified", severity: "S1" }),
  closedTicket({ id: "t_w19_6", key: "DRV-200",  type: "engineering", title: "Reduce taps per delivery (phase 1)", epicId: "ep_drv", sprintId: "sp_w19", authorId: "u_diana",   assigneeId: "u_devi",   storyPoints: 3, closedDaysAgo: 2, tags: ["mobile"] }),
  closedTicket({ id: "t_w19_7", key: "RTE-855",  type: "engineering", title: "Reroute scoring (pre-cutoff)",      epicId: "ep_rte", sprintId: "sp_w19", authorId: "u_albert",  assigneeId: "u_mira",   storyPoints: 2, closedDaysAgo: 0, priority: "P1", tags: ["routing"], status: "in_progress", carryOver: true }),
  closedTicket({ id: "t_w19_8", key: "BUG-4402", type: "bug",         title: "Stuck 'delivered' sync state",       epicId: "ep_drv", sprintId: "sp_w19", authorId: "u_ronaldo", assigneeId: "u_devi",   storyPoints: 2, closedDaysAgo: 0, priority: "P1", tags: ["mobile"], status: "review", carryOver: true, severity: "S2" }),

  // W18 - 5 shipped (29 pts); committed = 30 (1 pt slipped silently)
  closedTicket({ id: "t_w18_1", key: "CDN-3475", type: "engineering", title: "Daily MAPE baseline calc",          epicId: "ep_cdn", sprintId: "sp_w18", authorId: "u_albert",  assigneeId: "u_andre",  storyPoints: 5, closedDaysAgo: 9, tags: ["ml"] }),
  closedTicket({ id: "t_w18_2", key: "HUB-090",  type: "engineering", title: "Sortation-line API integration",    epicId: "ep_hub", sprintId: "sp_w18", authorId: "u_diana",   assigneeId: "u_mira",   storyPoints: 8, closedDaysAgo: 9, tags: ["sorting", "platform"] }),
  closedTicket({ id: "t_w18_3", key: "BUG-4385", type: "bug",         title: "Map tile failure when offline",     epicId: "ep_drv", sprintId: "sp_w18", authorId: "u_ronaldo", assigneeId: "u_devi",   storyPoints: 5, closedDaysAgo: 10, priority: "P1", tags: ["mobile"], status: "verified", severity: "S2" }),
  closedTicket({ id: "t_w18_4", key: "RTE-840",  type: "engineering", title: "Static feed schema spike",          epicId: "ep_rte", sprintId: "sp_w18", authorId: "u_albert",  assigneeId: "u_sari",   storyPoints: 8, closedDaysAgo: 11, tags: ["routing"] }),
  closedTicket({ id: "t_w18_5", key: "CDN-3478", type: "tech_task",   title: "Promotion rollback hook",           epicId: "ep_cdn", sprintId: "sp_w18", authorId: "u_andre",   assigneeId: "u_andre",  storyPoints: 3, closedDaysAgo: 8, tags: ["ml", "platform"] }),

  // W17 - 4 shipped (26 pts); committed = 28 (2 pt slip)
  closedTicket({ id: "t_w17_1", key: "MAD-300",  type: "engineering", title: "Madura station onboarding API",     epicId: "ep_mad", sprintId: "sp_w17", authorId: "u_albert",  assigneeId: "u_sari",   storyPoints: 8, closedDaysAgo: 16, priority: "P1", tags: ["4pl"] }),
  closedTicket({ id: "t_w17_2", key: "HUB-080",  type: "engineering", title: "Capacity signal contract",          epicId: "ep_hub", sprintId: "sp_w17", authorId: "u_diana",   assigneeId: "u_mira",   storyPoints: 5, closedDaysAgo: 17, tags: ["sorting"] }),
  closedTicket({ id: "t_w17_3", key: "BUG-4368", type: "bug",         title: "Auth refresh race on token rotate", epicId: null,     sprintId: "sp_w17", authorId: "u_ronaldo", assigneeId: "u_andre",  storyPoints: 5, closedDaysAgo: 18, priority: "P0", tags: ["auth"], status: "verified", severity: "S1" }),
  closedTicket({ id: "t_w17_4", key: "CDN-3450", type: "engineering", title: "Forecast staging dataset",          epicId: "ep_cdn", sprintId: "sp_w17", authorId: "u_albert",  assigneeId: "u_andre",  storyPoints: 8, closedDaysAgo: 16, tags: ["ml"] }),
];

// ─── Comments ───────────────────────────────────────────────────────
export const seedComments: Comment[] = [
  {
    id: "c_1",
    entityType: "ticket",
    entityId: "t_3504",
    parentCommentId: null,
    authorId: "u_sari",
    body: "Heads up @andre.halim - let's land the alert channel before drift gate flips on. Saves a noisy night.",
    mentions: ["u_andre"],
    createdAt: isoDate(addDays(today, -2)),
    editedAt: null,
    reactions: { "👍": ["u_andre"] },
    resolvedById: null,
  },
  {
    id: "c_2",
    entityType: "ticket",
    entityId: "t_3504",
    parentCommentId: "c_1",
    authorId: "u_andre",
    body: "On it. Channel hook merged in CDN-3496 already; just need to wire the threshold breach.",
    mentions: [],
    createdAt: isoDate(addDays(today, -1)),
    editedAt: null,
    reactions: {},
    resolvedById: null,
  },
  {
    id: "c_3",
    entityType: "ticket",
    entityId: "t_4421",
    parentCommentId: null,
    authorId: "u_ronaldo",
    body: "Confirmed reproducible on Pixel 8 + Samsung S23. Video attached internally.",
    mentions: [],
    createdAt: isoDate(addDays(today, -2)),
    editedAt: null,
    reactions: { "✅": ["u_devi", "u_sari"] },
    resolvedById: null,
  },
];

// ─── Notifications ──────────────────────────────────────────────────
export const seedNotifications: Notification[] = [
  {
    id: "n_1",
    userId: "u_andre",
    kind: "mention",
    body: "Sari mentioned you on CDN-3504",
    entityType: "ticket",
    entityKey: "CDN-3504",
    actorId: "u_sari",
    createdAt: isoDate(addDays(today, -2)),
    read: false,
    archived: false,
  },
  {
    id: "n_2",
    userId: "u_andre",
    kind: "assignment",
    body: "You were assigned BUG-4500",
    entityType: "ticket",
    entityKey: "BUG-4500",
    actorId: "u_diana",
    createdAt: isoDate(today),
    read: false,
    archived: false,
  },
  {
    id: "n_4",
    userId: "u_albert",
    kind: "sprint_commit",
    body: "Sprint W20 committed - 34 pts across 5 engineers",
    entityType: "sprint",
    entityKey: "W20-2026",
    createdAt: isoDate(addDays(today, -1)),
    read: true,
    archived: false,
  },
  {
    id: "n_5",
    userId: "u_diana",
    kind: "health_change",
    body: "Epic EPC-021 Driver experience moved to Blocked",
    entityType: "epic",
    entityKey: "EPC-021",
    createdAt: isoDate(addDays(today, -1)),
    read: false,
    archived: false,
  },
];

// ─── Activity ───────────────────────────────────────────────────────
export const seedActivity: ActivityEntry[] = [
  {
    id: "a_1",
    entityType: "ticket",
    entityId: "t_3504",
    actorId: "u_andre",
    action: "status_change",
    field: "status",
    beforeValue: "scheduled",
    afterValue: "in_progress",
    timestamp: isoDate(addDays(today, -1)),
    aiInfluenced: false,
  },
  {
    id: "a_2",
    entityType: "ticket",
    entityId: "t_3504",
    actorId: "u_andre",
    action: "ac_check",
    field: "ac",
    beforeValue: "MAPE deviation calc runs nightly",
    afterValue: "checked",
    timestamp: isoDate(addDays(today, -1)),
    aiInfluenced: false,
  },
  {
    id: "a_3",
    entityType: "ticket",
    entityId: "t_3505",
    actorId: "u_albert",
    action: "points_set",
    field: "story_points",
    beforeValue: "-",
    afterValue: "8",
    timestamp: isoDate(addDays(today, -2)),
    aiInfluenced: true,
  },
];
